### ISSUE TITLE
Revive the project

### ISSUE THREAD

**Issue by cstamas** [takari/maven-timeline#5]
I would like to revive this project, and make it work again as planned and keep it regularly released and updated to latest Maven versions. For this. we'd need the work done by forks, to get those back into this repository.

@danhaywood @schollD can you help me here?

No more needed than your agreement about this, no need for you to create PRs (if you do, the merrier), am just interested in your consent.

**Comment by danhaywood** [comment]
Fine by me, thanks. My fork has a tiny fix in it, you are welcome to bring
it back into the mainline if you wish, would like to be using an official
build, thanks for this initiative!

**Comment by cstamas** [comment]
1.8 version released, pending sync to central. Thanks all! Will push tags and set GH release once synced.

**Comment by schollD** [comment]
Great, thx! Feel free :)

**Comment by cstamas** [comment]
Sorry, but I already did it. To be frank, I spotted your commits being merged after I created this issue, so I assumed an "ok" from your side 😄

**Comment by cstamas** [comment]
Meaning, 1.8 w/ all the latest and greatest is already in Central.

**Comment by danhaywood** [comment]
Great stuff, thanks!
