### ISSUE TITLE
openDatabase is no longer available

### ISSUE THREAD

**Issue by csullivanupgrade** [takari/maven-timeline#8]
The openDatabase function is not available for Firefox or for [recent versions of Chrome/Chromium](https://developer.chrome.com/blog/deprecating-web-sql).

This results in the following when trying to open the timeline.html, from the developer console:
```
Uncaught ReferenceError: openDatabase is not defined
    at new TimeLineDb (database.js:5:3)
    at new TimeLineApp (app.js:30:21)
    at onload (timeline.html:23:41)
```

I have tried both Chrome Version `123.0.6312.124` and Firefox `125.0.1`.

**Comment by cstamas** [comment]
Fixed by https://github.com/takari/maven-timeline/pull/9
